const StudentsActionType = {
    FETCH_ALL_STUDENTS: "FETCH_ALL_STUDENTS",
    FETCH_STUDENT: "FETCH_STUDENT",
    ADD_STUDENT: "ADD_STUDENT",
    REMOVE_STUDENT: "REMOVE_STUDENT",
    FETCH_STUDENT_COUNT: "FETCH_STUDENT_COUNT",
    EDIT_STUDENT: "EDIT_STUDENT",
}

export default StudentsActionType